/**
 * Gamiarc - Central Games Registry
 * Source of truth for all games across homepage, catalogue, and game pages.
 */

export const GAMES = [
  {
    id: 'tic-tac-toe',
    slug: 'Gamiarc_tictactoe',
    name: 'Neon Tic-Tac-Toe',
    category: 'Strategy',
    genre: 'strategy',
    description: 'The classic game reimagined. Challenge the AI or play with a friend in real-time.',
    thumbnail: 'https://images.unsplash.com/photo-1611996575749-79a3a250f948?auto=format&fit=crop&w=600&q=80',
    route: '/games/Gamiarc_tictactoe',
    rating: 4.9,
    playersCount: '1-2',
    playersNumber: 9400,
    playTime: '1-3 min',
    featured: true,
    status: 'published',
    accentColor: '#818cf8',
    subgenre: 'Strategy • Classic',
  },
  {
    id: 'ludo',
    slug: 'Gamiarc_ludo',
    name: 'Neon Ludo',
    category: 'Board Game',
    genre: 'board',
    description: 'Classic Ludo reimagined with neon aesthetics. Race your tokens to the nexus before your rivals.',
    thumbnail: 'https://images.unsplash.com/photo-1611996575749-79a3a250f948?auto=format&fit=crop&w=600&q=80',
    route: '/games/Gamiarc_ludo',
    rating: 4.8,
    playersCount: '1-4',
    playersNumber: 8204,
    playTime: '15-30 min',
    featured: true,
    status: 'under-development',
    accentColor: '#06b6d4',
    subgenre: 'Board Game • Dice',
  },
  {
    id: 'sudoku',
    slug: 'sudoku',
    name: 'Zen Sudoku',
    category: 'Logic',
    genre: 'puzzle',
    description: 'Harmonize the numerical grid. A timeless puzzle experience for all skill levels.',
    thumbnail: 'https://images.unsplash.com/photo-1510074377623-8cf13fb86c08?auto=format&fit=crop&w=600&q=80',
    route: '#',
    rating: 4.9,
    playersCount: '1',
    playersNumber: 7300,
    playTime: '5-10 min',
    featured: true,
    status: 'coming-soon',
    accentColor: '#3b82f6',
    subgenre: 'Logic • Numbers',
  },
  {
    id: 'solitaire',
    slug: 'solitaire',
    name: 'Crystal Solitaire',
    category: 'Cards',
    genre: 'casual',
    description: 'Holographic solitaire in zero gravity. Sort the deck before the system reboots.',
    thumbnail: 'https://images.unsplash.com/photo-1580519542036-c47de6196ba5?auto=format&fit=crop&w=600&q=80',
    route: '#',
    rating: 4.7,
    playersCount: '1',
    playersNumber: 6100,
    playTime: '3-8 min',
    featured: true,
    status: 'coming-soon',
    accentColor: '#06b6d4',
    subgenre: 'Cards • Patience',
  },
  {
    id: 'neon-shadow',
    slug: 'neon-shadow',
    name: 'Neon Shadow',
    category: 'Action',
    genre: 'action',
    description: 'Infiltrate high-security corporate subnets in a fast-paced cyber thriller.',
    thumbnail: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDsJP519SqQzzaM3RbdZVsgw5PjDf7vYXoTZzhAW17NrjUm2r9SXVHCO67QyDp8Si9rRsoAYcrGeEw-dWwceTInbLgd6D5_1sehJdcaX59FLKA1oe13kRvAv6YXZ491_klfU3lmGjYMQKtBMVCsZUEfXo29aJoG2GJ52VjfQNW30loVZZ6ZVoSjYHuD5F_hoDkg2i_yArhjU3Js8cpHpYOVZBGFixH6fg1QswlUm2-NmvcEJC8qFj2fxWHgtuwnGIJbuEBds5xQaeSi',
    route: '#',
    rating: 4.9,
    playersCount: '1',
    playersNumber: 8200,
    playTime: '2-5 min',
    featured: false,
    status: 'coming-soon',
    accentColor: '#3b82f6',
    badge: 'New',
    subgenre: 'Action • Cyber-Thriller',
  },
  {
    id: 'cyber-drift',
    slug: 'cyber-drift',
    name: 'Cyber Drift',
    category: 'Sports',
    genre: 'sports',
    description: 'Neon highway racing against ghost drivers with hyper-responsive drifting physics.',
    thumbnail: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDy-OsrsW_olRd6K0LPqeoG8rzVYWlOYxKsvh0kFO6_e80L4yBngJAGlXrqZB5fbAQVdlQ8P0y7RVGobhdxko-UtwzBNGXeC9QjLJDYOJOkJzVeJig7puuybW1oiZHy9Jf-typ_bRUCJ2L20-6DIo6LhrWgpsTF3tsYV8oGxp8ZqshM4zVIH6Tjml_gQsj7A8y4HkiITRCjdiZ6TiB72_JXe7fiLI-rZJb5aYsyJPGvP0xlGBxxNg3IXIiTBZFJyQtde94Zu1Fu6WZg',
    route: '#',
    rating: 4.7,
    playersCount: '1',
    playersNumber: 1200,
    playTime: '2-4 min',
    featured: false,
    status: 'coming-soon',
    accentColor: '#818cf8',
    subgenre: 'Racing • Arcade',
  },
  {
    id: 'glitch-protocol',
    slug: 'glitch-protocol',
    name: 'Glitch Protocol',
    category: 'Strategy',
    genre: 'strategy',
    description: 'Turn-based system hacking puzzle. Exploit node vulnerabilities to breach the firewall.',
    thumbnail: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAYFXMoKuCBHnzPL26-c3yzQeB-EQRl_FFBfiUVnZvUYdJm8Ifa05A20ZYJ2P2dGyXImkMOXyJhJk8ItRZ19zvOV8Pfs8AdKLs8aPrWOOoDyfUrOJiaUXGw86CEqxKpNlTElrPRPnQWrZgCiqqkxzIscEeAyEFP_4446bqWCV_KO9tu5ypJNtkof0IzoLnEwk_2ulq6Sl_MmMVNCwzMv9XxfwzgRqJBxSErJYr8A7sPrkwtJefk-zEMm4rOVRTj_oBU0ZBZPHcSirbU',
    route: '#',
    rating: 4.5,
    playersCount: '1',
    playersNumber: 3100,
    playTime: '3-6 min',
    featured: false,
    status: 'coming-soon',
    accentColor: '#a855f7',
    subgenre: 'Strategy • Hacking',
  },
  {
    id: 'void-runner',
    slug: 'void-runner',
    name: 'Void Runner',
    category: 'RPG',
    genre: 'rpg',
    description: 'Explore procedurally generated neon dungeons and collect cyber relics in the void.',
    thumbnail: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAJHyl4qCjqrPd1RSWh-j8M77doHFhIEJcOW6FZnQfRaKU2ZntuGB5nbh_kKVsRHh42oRfhhUW9R88KDMq5ibv6RdCIK21iHLqCKyBeeuYF7TvQ7S9CF-XwpDIW8WPEBw1gDqkonD5S6-qTa5sIfBnHsWwxTV660YUkW6lwGY9ypbaABH3NxoGJvNn9POMQ_DOX96U5Yp3k_K6wPl1QJ3b51AXxHpn76IEDYf60hxeQMW5b3FV-TPeRmm1ywxPZ6ZSE_sRUyBnLyu3A',
    route: '#',
    rating: 4.8,
    playersCount: '1',
    playersNumber: 5500,
    playTime: '5-15 min',
    featured: false,
    status: 'coming-soon',
    accentColor: '#06b6d4',
    subgenre: 'RPG • Exploration',
  },
  {
    id: 'neural-link',
    slug: 'neural-link',
    name: 'Neural Link',
    category: 'Puzzle',
    genre: 'puzzle',
    description: 'Connect synaptic pathways across an expanding neural network before overload occurs.',
    thumbnail: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD4sReAOPWB2J6gHW4j_JfevZLhaR1LAKwi7FcNxEYabwdaScYjf6cLZhz6-p4_OrHhDOceo1PnPvZ3SX9zWFfTn8OHSaGyI6nVee5APshz6bjtO2AYFd883uwH5tMmY8KNT0d0V3T3fgTVMvL9V0DIlDl1SJhB0U11qLl-NyBotgfjSSuUn65-4OiZq56CMdxyv2wXYL7bziI95n5FP1A2cSffhQXI5kYuKcGisDB73CbOMZ1WwvVkdBfLRtKT73U8WEtILn0n16to',
    route: '#',
    rating: 4.3,
    playersCount: '1',
    playersNumber: 2800,
    playTime: '3-5 min',
    featured: false,
    status: 'coming-soon',
    accentColor: '#3b82f6',
    subgenre: 'Puzzle • Mind Games',
  },
  {
    id: 'data-breach',
    slug: 'data-breach',
    name: 'Data Breach',
    category: 'Action',
    genre: 'action',
    description: 'Bypass biometric scanners and stealth laser grids in this precision timing challenge.',
    thumbnail: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB-D-igWEBEE9q0hvq24Ym_6N2xjGLuCMSzLYrsuNN09c0UQsduOqpsL2MJ0PAflqybIfY4oL6GWgldDvsZJn0pB_0Ior-1aBrL32iAogTBMf4HqOM9z8B6_r6D1tnRT4wb9py-h9jjSzEcEmSZKSEE9dyo8h_PlfloYiIeVrvzME7DhPiirSBMif39Nh1VdK7efHyarvw6ALjn3h2spPbsB9uicBnx-t282nbj6HxYcl5L77t6d_1T8Duj47qJVEBl7YmIv1gFMzY6',
    route: '#',
    rating: 4.6,
    playersCount: '1',
    playersNumber: 4400,
    playTime: '2-4 min',
    featured: false,
    status: 'coming-soon',
    accentColor: '#f59e0b',
    subgenre: 'Action • Stealth',
  },
];

export function getFeaturedGames() {
  return GAMES.filter((g) => g.featured);
}

export function getGameById(id) {
  return GAMES.find((g) => g.id === id || g.slug === id);
}
